config/routes.rb
Blogapp::Application.routes.draw do
  devise_for :users
  resources :pictures

  get "publics/index"
  get "publics/article"
  get "publics/pictures"
  get "publics/profile"
  resources :diaries
  get ':id' => 'publics#article'

  

end

app/models/diary.rb
class Diary < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	mount_uploader :date, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @diary }
      else
        format.html { render action: 'new' }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_params
      params.require(:diary).permit(:title, :body, :comment_id, :status)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    render :layout => 'public'
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :date)
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
	layout 'public'
  def index
  	@diary = Diary.all
  end

  def article
  	@diary = Diary.where(id: params[:id]).first
  end
  def pictures
  	@pictures = Picture.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/views/diaries/_form.html.erb
<%= form_for(@diary) do |f| %>
  <% if @diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% @diary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br>
    <%= f.number_field :comment_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing diary</h1>

<%= render 'form' %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

app/views/diaries/index.html.erb
<h1>diary -日記-</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Comment</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.title %></td>
        <td><%= diary.body %></td>
        <td><%= diary.comment_id %></td>
        <td><%= diary.status %></td>
        <td><%= link_to 'Show', diary %></td>
        <td><%= link_to 'Edit', edit_diary_path(diary) %></td>
        <td><%= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diary', new_diary_path %>

app/views/diaries/new.html.erb
<h1>New diary</h1>

<%= render 'form' %>

<%= link_to 'Back', diaries_path %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @diary.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @diary.body %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @diary.comment_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @diary.status %>
</p>

<%= link_to 'Edit', edit_diary_path(@diary) %> |
<%= link_to 'Back', diaries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ちょこのブログ</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="mycss.css">
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.14.1/build/cssreset/cssreset-min.css">
</head>
<body>
	<div id="container">

	<div id="header">
	<h1>ちょこのブログ</h1>
	
    </div><!--header-->

    <div id="menu">

	<ul>
	 <li><a href="/profiles">プロフィール</a></li>
	　<li><a href="/publics/index">日記</a></li>
	 <li><a href="/pictures">写真</a></p></li>
	</ul>
    </div><!--menu-->

	<div id="main">		
     <% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>
	<%= yield %>
    </div><!--main-->

	<div id="footer">
	</div><!--footer-->
    </div><!--container-->

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ちょこのブログ</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="mycss.css">
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.14.1/build/cssreset/cssreset-min.css">
</head>
<body>
	<div id="container">

	<div id="header">
	<h1><b>ちょこのブログ</b></h1>
	<p>これはちょこのブログです。</p>
	<div class="badge">
		<%= image_tag "badge.png" %>
	</div>
	<%= image_tag "newhamu.png" %>

    </div><!--header-->

    <div id="menu">
	<ul>
	 <li><a href="/publics/profile">プロフィール</a></li>
	 <li><a href="/publics/index">日記</a></li>
	 <li><a href="/publics/pictures">写真</a></p></li>
	</ul>
    </div><!--menu-->

	<div id="main">
	<%= yield %>
    </div><!--main-->

	<div id="footer">
		<p>Copyright 2014,choco</p>
	</div><!--footer-->
    </div><!--container-->

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.file_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>pictures -写真-</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= picture.date %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= image_tag(@picture.date_url) if @picture.date.present? %>
</p>

<%= link_to 'Back', "/publics/pictures" %>

app/views/publics/article.html.erb
<h2><%= image_tag "newline.png" %><%= image_tag "icon.png" %><%=@diary.title%>　　<%=@diary.updated_at.strftime("%Y/%m/%d(%a) %H:%M")%></h2>
<p><%=@diary.body%></p>

app/views/publics/index.html.erb
<% @diary.each do |d| %>
<h2><%= image_tag "icon.png" %><%=d.title%>　　<%=d.updated_at.strftime("%Y/%m/%d(%a) %H:%M")%></h2>
<p><%=d.body[0..50]%>...</p>
<p><%= link_to '⇒read more!', "/#{d.id}" %></p>
<% end %>

app/views/publics/pictures.html.erb
<h1>写真</h1>

<table>
  <thead>
    <tr>
      
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= image_tag(picture.date_url,:width => '40') if picture.date.present? %></td>
        <td><%= picture.name %></td>
        <td><%= link_to 'Show', picture %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/publics/profile.html.erb
<h1>プロフィール</h1>
<p>私はちょこです。<br>
プログラミングの勉強をしています。<br>
まだまだ先は長そうです。<br>
<br>
名前：ちょこ<br>
誕生日：10/26<br>
血液型：Ａ型<br>
<br>
チョコレートBEST3<br>
１位　galbo<br>
２位　ブラックサンダー<br>
３位　ポッキー大人のミルク<br>
</p>